### ISSUE TITLE
about Style Augmentation

### ISSUE THREAD

**Issue by xiaoye-hhh** [ChuhaoZhou99/SAADG_VVIReID#1]
Nice wrok! I have read through the code and cannot find the Style Augmentation mentioned in the article. Where are the relevant details?

**Comment by ChuhaoZhou99** [comment]
@xiaoye-hhh Thank you for interesting in our work. You can find the details of Style Augmentation (SA) from line 235-250 in model.py.

**Comment by xiaoye-hhh** [comment]
Thank you!

**Comment by xiaoye-hhh** [comment]
Thank you!
