### ISSUE TITLE
模型权重

### ISSUE THREAD

**Issue by xyz999-skech** [ChuhaoZhou99/SAADG_VVIReID#3]
请问作者可以提供以下原文精度的模型权重吗？感谢！

**Comment by ChuhaoZhou99** [comment]
你好，感谢你对我们的工作感兴趣。我们已经发布了模型权重，请使用[链接](https://drive.google.com/drive/folders/1EkkjPq9Yz0Bexc6QhuUPwNfha9cwwUGc?usp=drive_link)进行下载。
